_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: c6df48ca-4bda-4d0b-9543-56e3662f0855
name: Echotech
mail: admin@email.com
slogan: ''
page:
  403: /user/login
  404: ''
  front: /page/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
